apiVersion: v2
name: helm-aptabase
description: Aptabase is an open-source analytics tool, an alternative to Google Analytics, for mobile, web, and desktop apps.
type: application
version: 1.0.0
appVersion: "1.1.0"
dependencies:
  - name: postgresql
    version: "16.4.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: clickhouse
    version: "8.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: clickhouse.enabled
