apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-postgresql
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  template:
    spec:
      containers:
        - name: wait
          image: busybox
          command: ['sh', '-c', 'until nc -z helm-aptabase-postgresql 5432; do sleep 5; done']
      restartPolicy: Never
