name: Release

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - main

jobs:
  build-helm-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.0
      - id: "configure-git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add postgresql and clickouhse repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          cd chart
          helm dependency update .
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
      - name: Run chart-testing (install)
        run: ct install --chart-dirs chart/ --charts chart/ --debug
      - run: kubectl get svc -A
